# CMake generated Testfile for 
# Source directory: /content/llama.cpp/tests
# Build directory: /content/llama.cpp/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test-tokenizer-0-bert-bge]=] "/content/llama.cpp/bin/test-tokenizer-0" "/content/llama.cpp/models/ggml-vocab-bert-bge.gguf")
set_tests_properties([=[test-tokenizer-0-bert-bge]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;40;add_test;/content/llama.cpp/tests/CMakeLists.txt;122;llama_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-command-r]=] "/content/llama.cpp/bin/test-tokenizer-0" "/content/llama.cpp/models/ggml-vocab-command-r.gguf")
set_tests_properties([=[test-tokenizer-0-command-r]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;40;add_test;/content/llama.cpp/tests/CMakeLists.txt;123;llama_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-deepseek-coder]=] "/content/llama.cpp/bin/test-tokenizer-0" "/content/llama.cpp/models/ggml-vocab-deepseek-coder.gguf")
set_tests_properties([=[test-tokenizer-0-deepseek-coder]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;40;add_test;/content/llama.cpp/tests/CMakeLists.txt;124;llama_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-deepseek-llm]=] "/content/llama.cpp/bin/test-tokenizer-0" "/content/llama.cpp/models/ggml-vocab-deepseek-llm.gguf")
set_tests_properties([=[test-tokenizer-0-deepseek-llm]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;40;add_test;/content/llama.cpp/tests/CMakeLists.txt;125;llama_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-falcon]=] "/content/llama.cpp/bin/test-tokenizer-0" "/content/llama.cpp/models/ggml-vocab-falcon.gguf")
set_tests_properties([=[test-tokenizer-0-falcon]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;40;add_test;/content/llama.cpp/tests/CMakeLists.txt;126;llama_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-gemma-4]=] "/content/llama.cpp/bin/test-tokenizer-0" "/content/llama.cpp/models/ggml-vocab-gemma-4.gguf")
set_tests_properties([=[test-tokenizer-0-gemma-4]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;40;add_test;/content/llama.cpp/tests/CMakeLists.txt;127;llama_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-gpt-2]=] "/content/llama.cpp/bin/test-tokenizer-0" "/content/llama.cpp/models/ggml-vocab-gpt-2.gguf")
set_tests_properties([=[test-tokenizer-0-gpt-2]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;40;add_test;/content/llama.cpp/tests/CMakeLists.txt;128;llama_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-llama-bpe]=] "/content/llama.cpp/bin/test-tokenizer-0" "/content/llama.cpp/models/ggml-vocab-llama-bpe.gguf")
set_tests_properties([=[test-tokenizer-0-llama-bpe]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;40;add_test;/content/llama.cpp/tests/CMakeLists.txt;129;llama_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-llama-spm]=] "/content/llama.cpp/bin/test-tokenizer-0" "/content/llama.cpp/models/ggml-vocab-llama-spm.gguf")
set_tests_properties([=[test-tokenizer-0-llama-spm]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;40;add_test;/content/llama.cpp/tests/CMakeLists.txt;130;llama_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-mpt]=] "/content/llama.cpp/bin/test-tokenizer-0" "/content/llama.cpp/models/ggml-vocab-mpt.gguf")
set_tests_properties([=[test-tokenizer-0-mpt]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;40;add_test;/content/llama.cpp/tests/CMakeLists.txt;131;llama_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-phi-3]=] "/content/llama.cpp/bin/test-tokenizer-0" "/content/llama.cpp/models/ggml-vocab-phi-3.gguf")
set_tests_properties([=[test-tokenizer-0-phi-3]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;40;add_test;/content/llama.cpp/tests/CMakeLists.txt;132;llama_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-qwen2]=] "/content/llama.cpp/bin/test-tokenizer-0" "/content/llama.cpp/models/ggml-vocab-qwen2.gguf")
set_tests_properties([=[test-tokenizer-0-qwen2]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;40;add_test;/content/llama.cpp/tests/CMakeLists.txt;133;llama_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-refact]=] "/content/llama.cpp/bin/test-tokenizer-0" "/content/llama.cpp/models/ggml-vocab-refact.gguf")
set_tests_properties([=[test-tokenizer-0-refact]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;40;add_test;/content/llama.cpp/tests/CMakeLists.txt;134;llama_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-0-starcoder]=] "/content/llama.cpp/bin/test-tokenizer-0" "/content/llama.cpp/models/ggml-vocab-starcoder.gguf")
set_tests_properties([=[test-tokenizer-0-starcoder]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;40;add_test;/content/llama.cpp/tests/CMakeLists.txt;135;llama_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizers-ggml-vocabs]=] "/content/llama.cpp/tests/test-tokenizers-repo.sh" "https://huggingface.co/ggml-org/vocabs" "/content/llama.cpp/models/ggml-vocabs")
set_tests_properties([=[test-tokenizers-ggml-vocabs]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "/content/llama.cpp/bin" _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;68;add_test;/content/llama.cpp/tests/CMakeLists.txt;138;llama_test_cmd;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-sampling]=] "/content/llama.cpp/bin/test-sampling")
set_tests_properties([=[test-sampling]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;152;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-reasoning-budget]=] "/content/llama.cpp/bin/test-reasoning-budget")
set_tests_properties([=[test-reasoning-budget]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;153;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-grammar-parser]=] "/content/llama.cpp/bin/test-grammar-parser")
set_tests_properties([=[test-grammar-parser]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;154;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-grammar-integration]=] "/content/llama.cpp/bin/test-grammar-integration")
set_tests_properties([=[test-grammar-integration]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;155;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-llama-grammar]=] "/content/llama.cpp/bin/test-llama-grammar")
set_tests_properties([=[test-llama-grammar]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;156;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-chat]=] "/content/llama.cpp/bin/test-chat")
set_tests_properties([=[test-chat]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "/content/llama.cpp" _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;157;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-json-schema-to-grammar]=] "/content/llama.cpp/bin/test-json-schema-to-grammar")
set_tests_properties([=[test-json-schema-to-grammar]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "/content/llama.cpp" _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;160;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-tokenizer-1-llama-spm]=] "/content/llama.cpp/bin/test-tokenizer-1-spm" "/content/llama.cpp/models/ggml-vocab-llama-spm.gguf")
set_tests_properties([=[test-tokenizer-1-llama-spm]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;40;add_test;/content/llama.cpp/tests/CMakeLists.txt;186;llama_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-llama-archs]=] "/content/llama.cpp/bin/test-llama-archs")
set_tests_properties([=[test-llama-archs]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;191;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-chat-peg-parser]=] "/content/llama.cpp/bin/test-chat-peg-parser")
set_tests_properties([=[test-chat-peg-parser]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;194;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-jinja]=] "/content/llama.cpp/bin/test-jinja")
set_tests_properties([=[test-jinja]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;195;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-jinja-py]=] "/content/llama.cpp/bin/test-jinja" "-py")
set_tests_properties([=[test-jinja-py]=] PROPERTIES  LABELS "python" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;40;add_test;/content/llama.cpp/tests/CMakeLists.txt;196;llama_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-chat-auto-parser]=] "/content/llama.cpp/bin/test-chat-auto-parser")
set_tests_properties([=[test-chat-auto-parser]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "/content/llama.cpp" _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;197;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-chat-template]=] "/content/llama.cpp/bin/test-chat-template")
set_tests_properties([=[test-chat-template]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;198;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-json-partial]=] "/content/llama.cpp/bin/test-json-partial")
set_tests_properties([=[test-json-partial]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;199;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-log]=] "/content/llama.cpp/bin/test-log")
set_tests_properties([=[test-log]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;200;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-peg-parser]=] "/content/llama.cpp/bin/test-peg-parser")
set_tests_properties([=[test-peg-parser]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;201;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-regex-partial]=] "/content/llama.cpp/bin/test-regex-partial")
set_tests_properties([=[test-regex-partial]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;212;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-download-model]=] "/usr/local/lib/python3.12/dist-packages/cmake/data/bin/cmake" "-DDEST=/content/llama.cpp/tinyllamas/stories15M-q4_0.gguf" "-DNAME=tinyllamas/stories15M-q4_0.gguf" "-DHASH=SHA256=66967fbece6dbe97886593fdbb73589584927e29119ec31f08090732d1861739" "-P" "/content/llama.cpp/cmake/download-models.cmake")
set_tests_properties([=[test-download-model]=] PROPERTIES  FIXTURES_SETUP "test-download-model" _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;223;add_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-thread-safety]=] "/content/llama.cpp/bin/test-thread-safety" "-m" "/content/llama.cpp/tinyllamas/stories15M-q4_0.gguf" "-ngl" "99" "-p" "The meaning of life is" "-n" "128" "-c" "256" "-ub" "32" "-np" "4" "-t" "2")
set_tests_properties([=[test-thread-safety]=] PROPERTIES  FIXTURES_REQUIRED "test-download-model" LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;231;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-arg-parser]=] "/content/llama.cpp/bin/test-arg-parser")
set_tests_properties([=[test-arg-parser]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;234;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-opt]=] "/content/llama.cpp/bin/test-opt")
set_tests_properties([=[test-opt]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;238;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-gguf]=] "/content/llama.cpp/bin/test-gguf")
set_tests_properties([=[test-gguf]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;240;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-backend-ops]=] "/content/llama.cpp/bin/test-backend-ops")
set_tests_properties([=[test-backend-ops]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;241;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-model-load-cancel]=] "/content/llama.cpp/bin/test-model-load-cancel")
set_tests_properties([=[test-model-load-cancel]=] PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;243;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-autorelease]=] "/content/llama.cpp/bin/test-autorelease")
set_tests_properties([=[test-autorelease]=] PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;244;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-backend-sampler]=] "/content/llama.cpp/bin/test-backend-sampler")
set_tests_properties([=[test-backend-sampler]=] PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;245;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-state-restore-fragmented]=] "/content/llama.cpp/bin/test-state-restore-fragmented" "-m" "/content/llama.cpp/tinyllamas/stories15M-q4_0.gguf")
set_tests_properties([=[test-state-restore-fragmented]=] PROPERTIES  FIXTURES_REQUIRED "test-download-model" LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;249;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-barrier]=] "/content/llama.cpp/bin/test-barrier")
set_tests_properties([=[test-barrier]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;254;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-quantize-fns]=] "/content/llama.cpp/bin/test-quantize-fns")
set_tests_properties([=[test-quantize-fns]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;255;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-quantize-perf]=] "/content/llama.cpp/bin/test-quantize-perf")
set_tests_properties([=[test-quantize-perf]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;256;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-rope]=] "/content/llama.cpp/bin/test-rope")
set_tests_properties([=[test-rope]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;257;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-mtmd-c-api]=] "/content/llama.cpp/bin/test-mtmd-c-api")
set_tests_properties([=[test-mtmd-c-api]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;262;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-gguf-model-data]=] "/content/llama.cpp/bin/test-gguf-model-data")
set_tests_properties([=[test-gguf-model-data]=] PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;40;add_test;/content/llama.cpp/tests/CMakeLists.txt;277;llama_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-quant-type-selection]=] "/content/llama.cpp/bin/test-quant-type-selection")
set_tests_properties([=[test-quant-type-selection]=] PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;280;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
add_test([=[test-alloc]=] "/content/llama.cpp/bin/test-alloc")
set_tests_properties([=[test-alloc]=] PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "/content/llama.cpp/tests/CMakeLists.txt;110;add_test;/content/llama.cpp/tests/CMakeLists.txt;292;llama_build_and_test;/content/llama.cpp/tests/CMakeLists.txt;0;")
